spring.application.name=automaat-api

spring.datasource.url=jdbc:postgresql://localhost:5432/automaat
spring.datasource.username=automaat
spring.datasource.password=automaat
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/automaat
spring.security.oauth2.resourceserver.jwt.audiences=automaat-api

automaat.upload-location=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
